sudo: required
dist: trusty
language: node_js
node_js: stable

env:
  global:
    - secure: "IohNfOWuyIac0O13YKuyPr02OhWzl1xRLEndXMxxHa9LLqlDX+tBW5WU6d8TZaubpQIUV6hiXg/0IrSBiUODrDzFVKluIDe39H8mJ1/9ktboWcDMHl4QvazZwy1KlIsKEljsa2evlu5BKsPIYVP0mqRULZscbm/RL2tPdP3WGeb/aQLHzjYJIiC4/fjF8Ug21kksKNQc56YIYqjmK01Klb/k6YY+rdn1CUYRk7crmXemloekSiaEJYydldSoZaD6zpqvycp48xO5qUAbdicyOuiYY+sjflnNGC5rUy9Kz7umjGHmEjoMBdEVjIQSfw+a7jBfa+IDExIgMpLXGPBBlXEYI/UeAql2dWFxhutdiVJNptWjshS0/cs2ygXtalOQYWH99F6bof6fZ3jFYlfEmrWZEFnw3DBtvztNHs98fbL+CBMpFujNo4HXYRrT99j3X47sS8/AFVlsloIfc/AcRLgAB4ECyDA37iALqlH5o5yLJVJhpOzlIZS141bZKLOwsM+K30PrPfqJV4+lkCCSHRl9cAA7z+ufHLcwdAvgLzF1l3iOvwj0788o3sKnI14cs+CZi65U71D5Cr0NePvbf6NoluxnqWLTH8qQscxfwTJW8/E4/+wX0CJr+J/VxkCt1cpZqgtYZQH4LgDC4Ts/70GRr8Fs8GMW2/FV7IH1o4c="
    - secure: "fUoYXY5CaPxwhdyn//ddSKCSR6uQTSGeNhZicIo0F0fyXOENHp6R30YO4ENAmzcM32F17Y1/GLgriY14GRHqnQXt2iBImpktFNhhdozcTDg9f4KcM2c4AeAgg3tb7f/S8K0KudvcVeVQWhKloYv89bYFM1QSF7cYp0qdj2HsaDn6bx+M7NCcwwrOq+9YNqoJmga3KpuNctQTYbNdGwK1FkWrcvpdi7hjJrTFLEQzTrcpOLwoki5AhOMdEz8kiNFRJkeBlS9LvTJ/+jqSbH9V39qtZSB5mGqgSRH7gfb6SRqSCRg1qqWgB0XJ6A2S3cJNXXEyvQQ5I4UMP0tEIYDqgGC7lU0Vi72ZuuwhNJlqtkWWp3dcd68vm4rA6CXFfPQPd8RVpM+GTPGVHFHcBiiKzlWNudCSNndKuEObNFC8EoSZHmACzGAy1ufU1+ooY7MkeQAYOdHJtrlwefpeDizGm8JviuZhPGDfIrmqRFF1FfQFH5bjSQSJZiEhYu8gBZEbY7F3452dHlwnsVFdij4d/iGuWDLpGweaD2TkEy0A0J0EW5aWsHTl9yNq9kMKhe/nWJ3Mm4Cjp4Ao+XJlH1ajytyJsuYZuK3zKVq7SfXNtoqvEso865pgW9ZxmYWrHb6azgVLIE/dGuPo0RQHfgJD8PLfgjAg89xyO77jUpvhEXI="

install:
  - npm install -g yo generator-hubot
  # adapter
  - npm install -g hubot-telegram
  # helpers
  - sudo apt-get install jq

script:
  - mkdir deploy
  - cd deploy
  - yo hubot --owner="Leo Arias <yo@elopio.net>" --name="eljaqueado_bot" --description="El bot del jáquerespeis" --adapter=telegram --defaults
  # scripts
  - npm install --save hubot-tweeter hubot-proxy
  - external_scripts=$(jq '. + ["hubot-tweeter", "hubot-proxy"]' < external-scripts.json)
  - echo $external_scripts > external-scripts.json
  # copy the proxy
  - cp ../adapter-proxy-config.coffee .

after_success:
  - cd ..
  - chmod 755 ./.push_heroku_deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.push_heroku_deploy.sh
