sudo: required
dist: trusty
language: node_js
node_js: stable

install:
  - npm install -g yo git+ssh://git@github.com:hubotio/generator-hubot#v1.0.0
  # adapter
  - npm install -g hubot-telegram
  # helpers
  - sudo apt-get install jq

script:
  - mkdir deploy
  - cd deploy
  - yo hubot --owner="Leo Arias <yo@elopio.net>" --name="eljaqueado_bot" --description="El bot del jáquerespeis" --adapter=telegram --defaults
  # external scripts
  - npm install --save hubot-plusplus hubot-redis-brain hubot-tweeter
  - external_scripts=$(jq '. + ["hubot-plusplus", "hubot-redis-brain", "hubot-tweeter"]' < external-scripts.json)
  - echo $external_scripts > external-scripts.json
  # local scripts
  - cp ../scripts/* scripts/

after_success:
  - cd ..
  - chmod 755 ./.push_heroku_deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.push_heroku_deploy.sh
