sudo: required
dist: trusty
language: node_js
node_js: stable

env:
  global:
    - secure: "B5293nYMbOcCf3q7fLpLuQvBnfgwKn99eo4NH+EggGpuVMiPG+nuzmEX0eJ7WATgJa8JCTGikoN9SBAVhRMNat/cUCi054MJ2jkefuDSVZlr0kIoRTZKkGFKOyXZx1hWcsJWFRrtQbwIgVJOUlkP3YaMSzDaRpmX3h406t23wA2lx9UOfXJl2bOqw0HIM1zmpe48Kq7E6y8jV++AlPrZ6cmr8pk3OhiIT9TyVTwtfptGSrF2GVMyTElDujycmlC5yusgVSVFmspVu1QnOeQmmLKuSZxqMJuMD40bq/5dxXndeNCRcBg6okR7xao12Vk2uIZgeUVrV485ddYdKEIcknBkt7EAurrierUH9yYU6aTITatViV9x/ejMoKaUzO7uC705GcyHk18qyqVFRp2lgMJKFirL42FZVLc7jDmFxiHkuohYB2X3aabSj6CEq5RF1c5YbSQjn4mCBJzoF6Sunz+W5tnvUJgUWWixJHkSX0sxHEjUrm131eRiOJbzrWmgV0AYpK4MT457V9HLmYAJV546KVaFfethlcr0sjJReOoVyBaYS7McPV/ZNCBteiWttpbtQPkIYDu2hOIGfwKTHLamzG4nFFt5NP+W0horWtN9q09C60CASfk0JpJznjG5vu+znpTxum61w9ZmRnCh4urTnJQh8e65/ISlHg+n90o="

install:
  - npm install -g yo generator-hubot hubot-telegram

script:
  - mkdir deploy
  - cd deploy
  - yo hubot --owner="Leo Arias <yo@elopio.net>" --name="eljaqueado_bot" --description="El bot del jáquerespeis" --adapter=telegram --defaults

after_success:
  - cd ..
  - chmod 755 ./.push_heroku_deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.push_heroku_deploy.sh
