sudo: required
dist: trusty
language: node_js
node_js: stable

env:
  global:
    - secure: "IohNfOWuyIac0O13YKuyPr02OhWzl1xRLEndXMxxHa9LLqlDX+tBW5WU6d8TZaubpQIUV6hiXg/0IrSBiUODrDzFVKluIDe39H8mJ1/9ktboWcDMHl4QvazZwy1KlIsKEljsa2evlu5BKsPIYVP0mqRULZscbm/RL2tPdP3WGeb/aQLHzjYJIiC4/fjF8Ug21kksKNQc56YIYqjmK01Klb/k6YY+rdn1CUYRk7crmXemloekSiaEJYydldSoZaD6zpqvycp48xO5qUAbdicyOuiYY+sjflnNGC5rUy9Kz7umjGHmEjoMBdEVjIQSfw+a7jBfa+IDExIgMpLXGPBBlXEYI/UeAql2dWFxhutdiVJNptWjshS0/cs2ygXtalOQYWH99F6bof6fZ3jFYlfEmrWZEFnw3DBtvztNHs98fbL+CBMpFujNo4HXYRrT99j3X47sS8/AFVlsloIfc/AcRLgAB4ECyDA37iALqlH5o5yLJVJhpOzlIZS141bZKLOwsM+K30PrPfqJV4+lkCCSHRl9cAA7z+ufHLcwdAvgLzF1l3iOvwj0788o3sKnI14cs+CZi65U71D5Cr0NePvbf6NoluxnqWLTH8qQscxfwTJW8/E4/+wX0CJr+J/VxkCt1cpZqgtYZQH4LgDC4Ts/70GRr8Fs8GMW2/FV7IH1o4c="

install:
  - npm install -g yo generator-hubot hubot-telegram

script:
  - mkdir deploy
  - cd deploy
  - yo hubot --owner="Leo Arias <yo@elopio.net>" --name="eljaqueado_bot" --description="El bot del jáquerespeis" --adapter=telegram --defaults

after_success:
  - cd ..
  - chmod 755 ./.push_heroku_deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.push_heroku_deploy.sh
